/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Employee;
import model.EmployeeHistory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author sumit
 */
public class CreateEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeJPanel
     */
    EmployeeHistory employeehistory;
    public CreateEmployeeJPanel(EmployeeHistory employeehistory) {
        initComponents();
        this.employeehistory = employeehistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmpNamelbl = new javax.swing.JLabel();
        EmpIdlbl = new javax.swing.JLabel();
        EmpAgelbl = new javax.swing.JLabel();
        EmpGenderlbl = new javax.swing.JLabel();
        EmpStartDatelbl = new javax.swing.JLabel();
        EmpLevellbl = new javax.swing.JLabel();
        EmpTeamlbl = new javax.swing.JLabel();
        EmpNametf = new javax.swing.JTextField();
        EmpIdtf = new javax.swing.JTextField();
        EmpAgetf = new javax.swing.JTextField();
        EmpGendertf = new javax.swing.JTextField();
        EmpLeveltf = new javax.swing.JTextField();
        EmpTeamtf = new javax.swing.JTextField();
        EmpPositionlbl = new javax.swing.JLabel();
        EmpContactlbl = new javax.swing.JLabel();
        EmpNumberlbl = new javax.swing.JLabel();
        EmpEmaillbl = new javax.swing.JLabel();
        EmpPositiontf = new javax.swing.JTextField();
        EmpNumbertf = new javax.swing.JTextField();
        EmpEmailtf = new javax.swing.JTextField();
        BtnSaveEmp = new javax.swing.JButton();
        EmpStartDatejdc = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(720, 370));

        EmpNamelbl.setText("Name:");

        EmpIdlbl.setText("Employee ID:");

        EmpAgelbl.setText("Age:");

        EmpGenderlbl.setText("Gender:");

        EmpStartDatelbl.setText("Start Date:");

        EmpLevellbl.setText("Level:");

        EmpTeamlbl.setText("Team Info:");

        EmpNametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpNametfActionPerformed(evt);
            }
        });
        EmpNametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpNametfKeyPressed(evt);
            }
        });

        EmpAgetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpAgetfKeyPressed(evt);
            }
        });

        EmpGendertf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpGendertfKeyPressed(evt);
            }
        });

        EmpTeamtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpTeamtfActionPerformed(evt);
            }
        });

        EmpPositionlbl.setText("Position Title: ");

        EmpContactlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmpContactlbl.setText("Contact Information");

        EmpNumberlbl.setText("Cell Phone Number:");

        EmpEmaillbl.setText("Email Address:");

        EmpPositiontf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpPositiontfActionPerformed(evt);
            }
        });

        EmpNumbertf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpNumbertfKeyPressed(evt);
            }
        });

        BtnSaveEmp.setText("Save");
        BtnSaveEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmpIdlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpNamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpAgelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpGenderlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpStartDatelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpLevellbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpTeamlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmpNametf)
                    .addComponent(EmpIdtf)
                    .addComponent(EmpAgetf)
                    .addComponent(EmpGendertf)
                    .addComponent(EmpLeveltf)
                    .addComponent(EmpTeamtf)
                    .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmpContactlbl)
                        .addGap(141, 141, 141))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnSaveEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmpNumberlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmpPositionlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EmpEmaillbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EmpPositiontf)
                                    .addComponent(EmpNumbertf)
                                    .addComponent(EmpEmailtf, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpNamelbl)
                    .addComponent(EmpNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpPositionlbl)
                    .addComponent(EmpPositiontf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIdlbl)
                    .addComponent(EmpIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpContactlbl))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpAgelbl)
                    .addComponent(EmpAgetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpNumberlbl)
                    .addComponent(EmpNumbertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpGenderlbl)
                    .addComponent(EmpGendertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpEmaillbl)
                    .addComponent(EmpEmailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EmpStartDatelbl)
                    .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpLevellbl)
                            .addComponent(EmpLeveltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(BtnSaveEmp)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpTeamlbl)
                    .addComponent(EmpTeamtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSaveEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveEmpActionPerformed
        // TODO add your handling code here:
        try{
            if (EmpStartDatejdc.getDate()!= null){                
                if (validate(EmpNametf.getText(),EmpIdtf.getText(),EmpAgetf.getText(),EmpStartDatejdc.getDate(),EmpNumbertf.getText(),EmpEmailtf.getText())){
            String EmpName = EmpNametf.getText();
            String EmpId = EmpIdtf.getText();
            int EmpAge = Integer.parseInt(EmpAgetf.getText());
            String EmpGender = EmpGendertf.getText();
            Date EmpStartDate = EmpStartDatejdc.getDate();
            String EmpLevel = EmpLeveltf.getText();
            String EmpTeam = EmpTeamtf.getText();
            String EmpPosition = EmpPositiontf.getText();
            Long EmpNumber = Long.parseLong(EmpNumbertf.getText());
            String EmpEmail = EmpEmailtf.getText();
            
            Employee newEmp = employeehistory.addNewValue();
            newEmp.setEmpName(EmpName);
            newEmp.setEmpId(EmpId);
            newEmp.setEmpAge(EmpAge);
            newEmp.setEmpGender(EmpGender);
            newEmp.setEmpStartDate(EmpStartDate);
            newEmp.setEmpLevel(EmpLevel);
            newEmp.setEmpTeam(EmpTeam);
            newEmp.setEmpPosition(EmpPosition);
            newEmp.setEmpNumber(EmpNumber);
            newEmp.setEmpEmail(EmpEmail);
            
            JOptionPane.showMessageDialog(this, "Successfully added new Employee");
            
            EmpNametf.setText("");
            EmpIdtf.setText("");
            EmpAgetf.setText("");
            EmpGendertf.setText("");
            EmpStartDatejdc.setDate(null);
            EmpLeveltf.setText("");
            EmpTeamtf.setText("");
            EmpPositiontf.setText("");
            EmpNumbertf.setText("");
            EmpEmailtf.setText("");
            }
            }
                else{
                    JOptionPane.showMessageDialog(EmpStartDatelbl, "Start Date cannot null", "Error", JOptionPane.ERROR_MESSAGE);
                }
        }
        catch(NumberFormatException e){
            System.out.print(e);
        }
    }//GEN-LAST:event_BtnSaveEmpActionPerformed

    private void EmpNametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpNametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpNametfActionPerformed

    private void EmpTeamtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpTeamtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpTeamtfActionPerformed

    private void EmpPositiontfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpPositiontfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpPositiontfActionPerformed

    private void EmpNumbertfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNumbertfKeyPressed
        // TODO add your handling code here:
        char empnumber = evt.getKeyChar();
        if(Character.isLetter(empnumber))
        {
            EmpNumbertf.setEditable(false);  
        }
        else {
            EmpNumbertf.setEditable(true); }
    }//GEN-LAST:event_EmpNumbertfKeyPressed

    private void EmpAgetfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpAgetfKeyPressed
        // TODO add your handling code here:
        char empage = evt.getKeyChar();
        if(Character.isLetter(empage))
        {
            EmpAgetf.setEditable(false);  
        }
        else {
            EmpAgetf.setEditable(true); }
    }//GEN-LAST:event_EmpAgetfKeyPressed

    private void EmpNametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNametfKeyPressed
        // TODO add your handling code here:
        char empname = evt.getKeyChar();
        if(Character.isLetter(empname))
        {
            EmpNametf.setEditable(false);  
        }
        else {
            EmpNametf.setEditable(true);  
        }
    }//GEN-LAST:event_EmpNametfKeyPressed

    private void EmpGendertfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpGendertfKeyPressed
        // TODO add your handling code here:
         char empgender = evt.getKeyChar();
        if(Character.isLetter(empgender))
        {
            EmpGendertf.setEditable(false);  
        }
        else {
            EmpGendertf.setEditable(true);  
        }
    }//GEN-LAST:event_EmpGendertfKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSaveEmp;
    private javax.swing.JLabel EmpAgelbl;
    private javax.swing.JTextField EmpAgetf;
    private javax.swing.JLabel EmpContactlbl;
    private javax.swing.JLabel EmpEmaillbl;
    private javax.swing.JTextField EmpEmailtf;
    private javax.swing.JLabel EmpGenderlbl;
    private javax.swing.JTextField EmpGendertf;
    private javax.swing.JLabel EmpIdlbl;
    private javax.swing.JTextField EmpIdtf;
    private javax.swing.JLabel EmpLevellbl;
    private javax.swing.JTextField EmpLeveltf;
    private javax.swing.JLabel EmpNamelbl;
    private javax.swing.JTextField EmpNametf;
    private javax.swing.JLabel EmpNumberlbl;
    private javax.swing.JTextField EmpNumbertf;
    private javax.swing.JLabel EmpPositionlbl;
    private javax.swing.JTextField EmpPositiontf;
    private com.toedter.calendar.JDateChooser EmpStartDatejdc;
    private javax.swing.JLabel EmpStartDatelbl;
    private javax.swing.JLabel EmpTeamlbl;
    private javax.swing.JTextField EmpTeamtf;
    // End of variables declaration//GEN-END:variables
    
    public static final Pattern pattern = 
    Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean EmailValidate(String emailStr) {
            Matcher matcher = pattern.matcher(emailStr);
            return matcher.find();
    }
    private boolean validate(String EmpName, String EmpId , String EmpAge, Date EmpStartDate, String EmpNumber, String EmpEmail) {
        
        if(EmpName.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Name Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpId.length()==0){
            JOptionPane.showMessageDialog(this, "Employee ID Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpAge.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Age Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpStartDate.after((java.util.Calendar.getInstance().getTime()))){
            JOptionPane.showMessageDialog(EmpStartDatelbl, "Start Date cannot be a future date", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        
        if(EmpNumber.length()>10 || EmpNumber.length()==0 || EmpNumber.length()<10){
            JOptionPane.showMessageDialog(this, "Enter a valid 10 digit Number", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpEmail.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Email Address Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        if(!EmailValidate(EmpEmail)){
            JOptionPane.showMessageDialog(this, "Enter Valid Employee Email", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        else {
            return true; }
    }

}
