/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.Employee;
import model.EmployeeHistory;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sumit
 */
public class ViewEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmployeeJPanel
     */
    EmployeeHistory emphistory;
    public ViewEmployeeJPanel(EmployeeHistory emphistory) {
        initComponents();
        this.emphistory = emphistory;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)EmpJTable.getModel();
        model.setRowCount(0);
        for(Employee employees: emphistory.getHistory()){
        
            Object[] row = new Object[10];
            row[0] = employees.getEmpName();
            row[1] = employees.getEmpId();
            row[2] = employees.getEmpAge();
            row[3] = employees.getEmpGender();
            row[4] = employees.getEmpStartDate();
            row[5] = employees.getEmpLevel();
            row[6] = employees.getEmpTeam();
            row[7] = employees.getEmpPosition();
            row[8] = employees.getEmpNumber();
            row[9] = employees.getEmpEmail();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmpJTable = new javax.swing.JTable();
        EmpNamelbl = new javax.swing.JLabel();
        EmpIdlbl = new javax.swing.JLabel();
        EmpAgelbl = new javax.swing.JLabel();
        EmpGenderlbl = new javax.swing.JLabel();
        EmpStartDatelbl = new javax.swing.JLabel();
        EmpLevellbl = new javax.swing.JLabel();
        EmpNametf = new javax.swing.JTextField();
        EmpIdtf = new javax.swing.JTextField();
        EmpAgetf = new javax.swing.JTextField();
        EmpGendertf = new javax.swing.JTextField();
        EmpLeveltf = new javax.swing.JTextField();
        EmpStartDatejdc = new com.toedter.calendar.JDateChooser();
        EmpTeamlbl = new javax.swing.JLabel();
        EmpNumberlbl = new javax.swing.JLabel();
        EmpEmaillbl = new javax.swing.JLabel();
        EmpTeamtf = new javax.swing.JTextField();
        EmpNumbertf = new javax.swing.JTextField();
        EmpEmailtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtnDeleteEmp = new javax.swing.JButton();
        BtnUpdateEmp = new javax.swing.JButton();
        BtnViewEmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EmpPositiontf = new javax.swing.JTextField();
        lblImagePreview = new javax.swing.JLabel();
        lblImagePreview1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(720, 406));

        EmpJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell Phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmpJTable);

        EmpNamelbl.setText("Name:");

        EmpIdlbl.setText("Employee ID:");

        EmpAgelbl.setText("Age:");

        EmpGenderlbl.setText("Gender:");

        EmpStartDatelbl.setText("Start Date:");

        EmpLevellbl.setText("Level:");

        EmpNametf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpNametfKeyPressed(evt);
            }
        });

        EmpAgetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpAgetfKeyPressed(evt);
            }
        });

        EmpGendertf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpGendertfKeyPressed(evt);
            }
        });

        EmpTeamlbl.setText("Team Info:");

        EmpNumberlbl.setText("Cell Phone Number:");

        EmpEmaillbl.setText("Email Address:");

        EmpNumbertf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmpNumbertfKeyPressed(evt);
            }
        });

        jLabel10.setText("Contact Information");

        BtnDeleteEmp.setText("Delete");
        BtnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteEmpActionPerformed(evt);
            }
        });

        BtnUpdateEmp.setText("Update");
        BtnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateEmpActionPerformed(evt);
            }
        });

        BtnViewEmp.setText("View");
        BtnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewEmpActionPerformed(evt);
            }
        });

        jLabel1.setText("Position:");

        lblImagePreview.setText("Image Preview:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmpLevellbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpStartDatelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpGenderlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpAgelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpNamelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpIdlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpIdtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnViewEmp)
                                        .addGap(31, 31, 31)
                                        .addComponent(BtnUpdateEmp)
                                        .addGap(27, 27, 27)
                                        .addComponent(BtnDeleteEmp)
                                        .addGap(208, 208, 208))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EmpNumberlbl)
                                                    .addComponent(EmpEmaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EmpPositiontf)
                                                    .addComponent(EmpNumbertf)
                                                    .addComponent(EmpEmailtf)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(EmpTeamlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EmpTeamtf)))
                                        .addGap(198, 198, 198))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmpAgetf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10))
                                    .addComponent(EmpGendertf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmpLeveltf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(lblImagePreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagePreview1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeleteEmp)
                    .addComponent(BtnUpdateEmp)
                    .addComponent(BtnViewEmp))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpNamelbl)
                    .addComponent(EmpNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpTeamlbl)
                    .addComponent(EmpTeamtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIdlbl)
                    .addComponent(EmpIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(EmpPositiontf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpAgetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpAgelbl)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpGenderlbl)
                    .addComponent(EmpGendertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpNumberlbl)
                    .addComponent(EmpNumbertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmpStartDatelbl))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmpEmaillbl)
                        .addComponent(EmpEmailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpLevellbl)
                    .addComponent(EmpLeveltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagePreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImagePreview1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateEmpActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = EmpJTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        if (validate(EmpNametf.getText(),EmpIdtf.getText(),EmpAgetf.getText(),EmpStartDatejdc.getDate(),EmpNumbertf.getText(),EmpEmailtf.getText())){    
        String EmpName = EmpNametf.getText();
        String EmpId = EmpIdtf.getText();
        int EmpAge = Integer.parseInt(EmpAgetf.getText());
        String EmpGender = EmpGendertf.getText();
        Date EmpstartDate = EmpStartDatejdc.getDate();
        String EmpLevel = EmpLeveltf.getText();
        String EmpTeam = EmpTeamtf.getText();
        String EmpPosition = EmpPositiontf.getText();
        Long EmpNumber = Long.parseLong(EmpNumbertf.getText());
        String EmpEmail = EmpEmailtf.getText();
        
        for(Employee employees: emphistory.getHistory()){
            if (EmpId.equals(employees.getEmpId())){
                emphistory.deleteEmployee(employees);
                break;
            }
        }
        Employee selEmp = emphistory.addNewValue();
        selEmp.setEmpName(EmpName);
        selEmp.setEmpId(EmpId);
        selEmp.setEmpAge(EmpAge);
        selEmp.setEmpGender(EmpGender);
        selEmp.setEmpStartDate(EmpstartDate);
        selEmp.setEmpLevel(EmpLevel);
        selEmp.setEmpTeam(EmpTeam);
        selEmp.setEmpPosition(EmpPosition);
        selEmp.setEmpNumber(EmpNumber);
        selEmp.setEmpEmail(EmpEmail);
        
        JOptionPane.showMessageDialog(this, "Employee has been Updated");
        
        EmpNametf.setText("");
        EmpIdtf.setText("");
        EmpAgetf.setText("");
        EmpGendertf.setText("");
        EmpStartDatejdc.setDate(null);
        EmpLeveltf.setText("");
        EmpTeamtf.setText("");
        EmpPositiontf.setText("");
        EmpNumbertf.setText("");
        EmpEmailtf.setText("");
        populateTable();
        }
    }//GEN-LAST:event_BtnUpdateEmpActionPerformed

    private void BtnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteEmpActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpJTable.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to delete","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel model = (DefaultTableModel) EmpJTable.getModel();
        String EmpId = model.getValueAt(selectedRowIndex, 1).toString();
        for(Employee employees: emphistory.getHistory()){
            if (EmpId.equals(employees.getEmpId())){
                emphistory.deleteEmployee(employees);
                System.out.print("employee found in history");
                break;
            }
        }
        EmpNametf.setText("");
        EmpIdtf.setText("");
        EmpAgetf.setText("");
        EmpGendertf.setText("");
        EmpStartDatejdc.setDate(null);
        EmpLeveltf.setText("");
        EmpTeamtf.setText("");
        EmpPositiontf.setText("");
        EmpNumbertf.setText("");
        EmpEmailtf.setText("");
        JOptionPane.showMessageDialog(this, "Employee has been deleted!!");
        populateTable();
    }//GEN-LAST:event_BtnDeleteEmpActionPerformed

    private void BtnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewEmpActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpJTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) EmpJTable.getModel();
        //ImageIcon i = null;
        EmpNametf.setText(model.getValueAt(selectedRowIndex, 0).toString());
        EmpIdtf.setText(model.getValueAt(selectedRowIndex, 1).toString());
        String id = model.getValueAt(selectedRowIndex, 1).toString();
        EmpAgetf.setText(model.getValueAt(selectedRowIndex, 2).toString());
        EmpGendertf.setText(model.getValueAt(selectedRowIndex, 3).toString());
        EmpStartDatejdc.setDate((Date) model.getValueAt(selectedRowIndex, 4));
        EmpLeveltf.setText(model.getValueAt(selectedRowIndex, 5).toString());
        EmpTeamtf.setText(model.getValueAt(selectedRowIndex, 6).toString());
        EmpPositiontf.setText(model.getValueAt(selectedRowIndex, 7).toString());
        EmpNumbertf.setText(model.getValueAt(selectedRowIndex, 8).toString());
        EmpEmailtf.setText(model.getValueAt(selectedRowIndex, 9).toString());
        for(Employee emp:emphistory.getHistory()){
            if(id.equals(emp.getEmpId()) && emp.getImage()!=null){
                lblImagePreview1.setIcon(new ImageIcon(emp.getImage()));
        }
            if(emp.getImage()==null){
                System.out.print("Image not saved");
            }
        }
        
    }//GEN-LAST:event_BtnViewEmpActionPerformed

    private void EmpNumbertfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNumbertfKeyPressed
        // TODO add your handling code here:
                char empnumber = evt.getKeyChar();
        if(Character.isLetter(empnumber))
        {
            EmpNumbertf.setEditable(false);  
        }
        else {
            EmpNumbertf.setEditable(true); }
    }//GEN-LAST:event_EmpNumbertfKeyPressed

    private void EmpAgetfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpAgetfKeyPressed
        // TODO add your handling code here:
        char empage = evt.getKeyChar();
        if(Character.isLetter(empage))
        {
            EmpAgetf.setEditable(false);  
        }
        else {
            EmpAgetf.setEditable(true); }
    }//GEN-LAST:event_EmpAgetfKeyPressed

    private void EmpNametfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpNametfKeyPressed
        // TODO add your handling code here:
        char empname = evt.getKeyChar();
        if(Character.isLetter(empname))
        {
            EmpNametf.setEditable(false);  
        }
        else {
            EmpNametf.setEditable(true);  
        }
    }//GEN-LAST:event_EmpNametfKeyPressed

    private void EmpGendertfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmpGendertfKeyPressed
        // TODO add your handling code here:
        char empgender = evt.getKeyChar();
        if(Character.isLetter(empgender))
        {
            EmpGendertf.setEditable(false);  
        }
        else {
            EmpGendertf.setEditable(true);  
        }
    }//GEN-LAST:event_EmpGendertfKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteEmp;
    private javax.swing.JButton BtnUpdateEmp;
    private javax.swing.JButton BtnViewEmp;
    private javax.swing.JLabel EmpAgelbl;
    private javax.swing.JTextField EmpAgetf;
    private javax.swing.JLabel EmpEmaillbl;
    private javax.swing.JTextField EmpEmailtf;
    private javax.swing.JLabel EmpGenderlbl;
    private javax.swing.JTextField EmpGendertf;
    private javax.swing.JLabel EmpIdlbl;
    private javax.swing.JTextField EmpIdtf;
    private javax.swing.JTable EmpJTable;
    private javax.swing.JLabel EmpLevellbl;
    private javax.swing.JTextField EmpLeveltf;
    private javax.swing.JLabel EmpNamelbl;
    private javax.swing.JTextField EmpNametf;
    private javax.swing.JLabel EmpNumberlbl;
    private javax.swing.JTextField EmpNumbertf;
    private javax.swing.JTextField EmpPositiontf;
    private com.toedter.calendar.JDateChooser EmpStartDatejdc;
    private javax.swing.JLabel EmpStartDatelbl;
    private javax.swing.JLabel EmpTeamlbl;
    private javax.swing.JTextField EmpTeamtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JLabel lblImagePreview1;
    // End of variables declaration//GEN-END:variables

    public static final Pattern pattern = 
    Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean EmailValidate(String emailStr) {
            Matcher matcher = pattern.matcher(emailStr);
            return matcher.find();
    }
    private boolean validate(String EmpName, String EmpId , String EmpAge, Date EmpStartDate, String EmpNumber, String EmpEmail) {
        
        if(EmpName.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Name Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpId.length()==0){
            JOptionPane.showMessageDialog(this, "Employee ID Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpAge.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Age Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpStartDate.after((java.util.Calendar.getInstance().getTime()))){
            JOptionPane.showMessageDialog(EmpStartDatelbl, "Start Date cannot be a future date", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        
        if(EmpNumber.length()>10 || EmpNumber.length()==0 || EmpNumber.length()<10){
            JOptionPane.showMessageDialog(this, "Enter a valid 10 digit Number", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        
        if(EmpEmail.length()==0){
            JOptionPane.showMessageDialog(this, "Employee Email Address Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        if(!EmailValidate(EmpEmail)){
            JOptionPane.showMessageDialog(this, "Enter Valid Employee Email", "Error", JOptionPane.ERROR_MESSAGE);
            
            return false;
        }
        else {
            return true; }
    }
}

