/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.Employee;
import model.EmployeeHistory;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Arrays;
import javax.swing.JList;
/**
 *
 * @author sumit
 */
public class ViewEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEmployeeJPanel
     */
    EmployeeHistory emphistory;
    public ViewEmployeeJPanel(EmployeeHistory emphistory) {
        initComponents();
        this.emphistory = emphistory;
        populateTable();
    }
    
    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel)EmpJTable.getModel();
        System.out.println(model);
        model.setRowCount(0);
        System.out.println(model);
        for(Employee employees: emphistory.getHistory()){
        
            Object[] row = new Object[10];
            row[0] = employees.getEmpName();
            row[1] = employees.getEmpId();
            row[2] = employees.getEmpAge();
            row[3] = employees.getEmpGender();
            row[4] = employees.getEmpStartDate();
            row[5] = employees.getEmpLevel();
            row[6] = employees.getEmpTeam();
            row[7] = employees.getEmpPosition();
            row[8] = employees.getEmpNumber();
            row[9] = employees.getEmpEmail();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmpJTable = new javax.swing.JTable();
        EmpNamelbl = new javax.swing.JLabel();
        EmpIdlbl = new javax.swing.JLabel();
        EmpAgelbl = new javax.swing.JLabel();
        EmpGenderlbl = new javax.swing.JLabel();
        EmpStartDatelbl = new javax.swing.JLabel();
        EmpLevellbl = new javax.swing.JLabel();
        EmpNametf = new javax.swing.JTextField();
        EmpIdtf = new javax.swing.JTextField();
        EmpAgetf = new javax.swing.JTextField();
        EmpGendertf = new javax.swing.JTextField();
        EmpLeveltf = new javax.swing.JTextField();
        EmpStartDatejdc = new com.toedter.calendar.JDateChooser();
        EmpTeamlbl = new javax.swing.JLabel();
        EmpNumberlbl = new javax.swing.JLabel();
        EmpEmaillbl = new javax.swing.JLabel();
        EmpTeamtf = new javax.swing.JTextField();
        EmpNumbertf = new javax.swing.JTextField();
        EmpEmailtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtnDeleteEmp = new javax.swing.JButton();
        BtnUpdateEmp = new javax.swing.JButton();
        BtnViewEmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        EmpPositiontf = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(720, 406));

        EmpJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Cell Phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EmpJTable);

        EmpNamelbl.setText("Name:");

        EmpIdlbl.setText("Employee ID:");

        EmpAgelbl.setText("Age:");

        EmpGenderlbl.setText("Gender:");

        EmpStartDatelbl.setText("Start Date:");

        EmpLevellbl.setText("Level:");

        EmpTeamlbl.setText("Team Info:");

        EmpNumberlbl.setText("Cell Phone Number:");

        EmpEmaillbl.setText("Email Address:");

        jLabel10.setText("Contact Information");

        BtnDeleteEmp.setText("Delete");
        BtnDeleteEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteEmpActionPerformed(evt);
            }
        });

        BtnUpdateEmp.setText("Update");
        BtnUpdateEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateEmpActionPerformed(evt);
            }
        });

        BtnViewEmp.setText("View");
        BtnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewEmpActionPerformed(evt);
            }
        });

        jLabel1.setText("Position:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(168, 168, 168))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmpLevellbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpStartDatelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpGenderlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpAgelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpNamelbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmpIdlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpNametf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpIdtf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnViewEmp)
                                        .addGap(31, 31, 31)
                                        .addComponent(BtnUpdateEmp)
                                        .addGap(27, 27, 27)
                                        .addComponent(BtnDeleteEmp)
                                        .addGap(208, 208, 208))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(EmpNumberlbl)
                                                    .addComponent(EmpEmaillbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(EmpPositiontf, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                                    .addComponent(EmpNumbertf)
                                                    .addComponent(EmpEmailtf)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(EmpTeamlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(EmpTeamtf)))
                                        .addGap(198, 198, 198))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EmpAgetf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127)
                                        .addComponent(jLabel10))
                                    .addComponent(EmpGendertf, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmpLeveltf, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnDeleteEmp)
                    .addComponent(BtnUpdateEmp)
                    .addComponent(BtnViewEmp))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpNamelbl)
                    .addComponent(EmpNametf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpTeamlbl)
                    .addComponent(EmpTeamtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIdlbl)
                    .addComponent(EmpIdtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(EmpPositiontf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpAgetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpAgelbl)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpGenderlbl)
                    .addComponent(EmpGendertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpNumberlbl)
                    .addComponent(EmpNumbertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EmpStartDatejdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EmpStartDatelbl))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmpEmaillbl)
                        .addComponent(EmpEmailtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpLevellbl)
                    .addComponent(EmpLeveltf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdateEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateEmpActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = EmpJTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) EmpJTable.getModel();
        Employee selEmp=(Employee)model.getValueAt(selectedRowIndex,0);
        
        String EmpName = EmpNametf.getText();
        String EmpId = EmpIdtf.getText();
        int EmpAge = Integer.parseInt(EmpAgetf.getText());
        String EmpGender = EmpGendertf.getText();
        Date EmpstartDate = EmpStartDatejdc.getDate();
        String EmpLevel = EmpLeveltf.getText();
        String EmpTeam = EmpTeamtf.getText();
        String EmpPosition = EmpPositiontf.getText();
        int EmpNumber = Integer.parseInt(EmpNumbertf.getText());
        String EmpEmail = EmpEmailtf.getText();
        
        selEmp.setEmpName(EmpName);
        selEmp.setEmpId(EmpId);
        selEmp.setEmpAge(EmpAge);
        selEmp.setEmpGender(EmpGender);
        selEmp.setEmpStartDate(EmpstartDate);
        selEmp.setEmpLevel(EmpLevel);
        selEmp.setEmpTeam(EmpTeam);
        selEmp.setEmpPosition(EmpPosition);
        selEmp.setEmpNumber(EmpNumber);
        selEmp.setEmpEmail(EmpEmail);
        
        JOptionPane.showMessageDialog(this, "Employee has been Updated");
        
        EmpNametf.setText("");
        EmpIdtf.setText("");
        EmpAgetf.setText("");
        EmpGendertf.setText("");
        EmpStartDatejdc.setDate(null);
        EmpLeveltf.setText("");
        EmpTeamtf.setText("");
        EmpPositiontf.setText("");
        EmpNumbertf.setText("");
        EmpEmailtf.setText("");
    }//GEN-LAST:event_BtnUpdateEmpActionPerformed

    private void BtnDeleteEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteEmpActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpJTable.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a record to delete","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) EmpJTable.getModel();
        Employee selectedEmployee=(Employee) model.getValueAt(selectedRowIndex, 0);
        //Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex, 0);
        
        emphistory.deleteEmployee(selectedEmployee);
        JOptionPane.showMessageDialog(this, "Employee has been deleted!!");
        
        populateTable();
    }//GEN-LAST:event_BtnDeleteEmpActionPerformed

    private void BtnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewEmpActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = EmpJTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        System.out.println(selectedRowIndex);
        DefaultTableModel model = (DefaultTableModel) EmpJTable.getModel();
        System.out.println(model.getClass().getSimpleName());
        System.out.println(model.getClass().getName());
        Employee selectedEmployee=(Employee)model.getValueAt(selectedRowIndex, 0);
        System.out.println("ss");          
        EmpNametf.setText(selectedEmployee.getEmpName());
        EmpIdtf.setText(selectedEmployee.getEmpId());
        EmpAgetf.setText(String.valueOf(selectedEmployee.getEmpAge()));
        EmpGendertf.setText(selectedEmployee.getEmpGender());
        EmpStartDatejdc.setDate(selectedEmployee.getEmpStartDate());
        EmpLeveltf.setText(selectedEmployee.getEmpLevel());
        EmpTeamtf.setText(selectedEmployee.getEmpTeam());
        EmpPositiontf.setText(selectedEmployee.getEmpPosition());
        EmpNumbertf.setText(String.valueOf(selectedEmployee.getEmpNumber()));
        EmpEmailtf.setText(selectedEmployee.getEmpEmail());
    }//GEN-LAST:event_BtnViewEmpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDeleteEmp;
    private javax.swing.JButton BtnUpdateEmp;
    private javax.swing.JButton BtnViewEmp;
    private javax.swing.JLabel EmpAgelbl;
    private javax.swing.JTextField EmpAgetf;
    private javax.swing.JLabel EmpEmaillbl;
    private javax.swing.JTextField EmpEmailtf;
    private javax.swing.JLabel EmpGenderlbl;
    private javax.swing.JTextField EmpGendertf;
    private javax.swing.JLabel EmpIdlbl;
    private javax.swing.JTextField EmpIdtf;
    private javax.swing.JTable EmpJTable;
    private javax.swing.JLabel EmpLevellbl;
    private javax.swing.JTextField EmpLeveltf;
    private javax.swing.JLabel EmpNamelbl;
    private javax.swing.JTextField EmpNametf;
    private javax.swing.JLabel EmpNumberlbl;
    private javax.swing.JTextField EmpNumbertf;
    private javax.swing.JTextField EmpPositiontf;
    private com.toedter.calendar.JDateChooser EmpStartDatejdc;
    private javax.swing.JLabel EmpStartDatelbl;
    private javax.swing.JLabel EmpTeamlbl;
    private javax.swing.JTextField EmpTeamtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
